### ISSUE TITLE
itGRN problem

### ISSUE THREAD

**Issue by LiangMingxuan00** [ChanghanGitHub/exFINDER#1]
Hello, thank you very much for this fantastic tool!

When I run the ItGRN, I got this warning message but it seems like some information is missed. How to fix it problem?

> ltGRN <- get_ltGRN(Target = target.gene, DB = exFINDER.Z)
Warning messages:
1: In get_ltGRN(Target = target.gene, DB = exFINDER.Z) :
  The following target genes have been ignored: 

2: In get_ltGRN(Target = target.gene, DB = exFINDER.Z) : Overlap found!

**Comment by ChanghanGitHub** [comment]
Hi Mingxuan,

The first warning "The following target genes have been ignored:..." means for some of the target genes, no corresponding ltGRNs were inferred by exFINDER. This may be due to: 1. these target genes are not recorded in the exFINDER-DB, or 2. no ligand was inferred that can connect these target genes (with the L-R-TF-T structure).  

The second warning "Overlap found!" means some genes have two or more roles (ligand, receptor, TF, or target). You can fix this by running "fix_OverLap" function ( i.e., "exSigNet <- fix_OverLap(exSigNet)" ).

**Comment by LiangMingxuan00** [comment]
Many thanks for your answer

Best,
Mingxuan
